export default [
  "Archäologie",
  "Astronomie",
  "Basis Antike mit Studienschwerpunkt Griechisch",
  "Basis Antike mit Studienschwerpunkt Latein",
  "Betriebswirtschaftslehre",
  "Biochemie und Molekularbiologie",
  "Biologie",
  "Central As ian Studies",
  "Chemie und Molekulare Wissenschaften",
  "Deutsche Sprach- und Literaturwissenschaft",
  "Eastern European Studies",
  "English",
  "Erdwissenschaften (Geologie)",
  "Erziehungswissenschaft",
  "Geographie",
  "Geschichte",
  "Grundlagen des Rechts",
  "Humanmedizin",
  "Informatik",
  "Interreligiöse Studien",
  "Islamic and Middle Eastern Studies",
  "Italienische Sprach- und Literaturwissenschaft",
  "Judaistik",
  "Klassische Philologie mit Schwerpunkt Griechisch",
  "Klassische Philologie mit Schwerpunkt Latein",
  "Kriminologie",
  "Kulturgeschichte und Archäologie des vorislamischen",
  "Palästina / Israel",
  "Kunstgeschichte",
  "Langue et Littérature françaises",
  "Linguistik",
  "Mathematik",
  "Musikwissenschaft",
  "Nachhaltige Entwicklung",
  "Neurowissenschaft",
  "Obligationenrecht und Wirtschaftsrecht",
  "Öffentliches Recht",
  "Pharmazeutische Wissenschaften",
  "Philosophie",
  "Philosophie des Geistes",
  "Physik",
  "Psychologie",
  "Rechtswissenschaft",
  "Science of Religion",
  "Slavistik",
  "Sozialanthropologie",
  "Sozialwissenschaften",
  "Sozialwissenschaften mit Schwerpunkt Kommunikations-und Medienwissenschaft",
  "Sozialwissenschaften mit Schwerpunkt Soziologie",
  "Spanische Sprach- und Literaturwissenschaft",
  "Sportwissenschaft",
  "Staatsrecht und Staatstheorie",
  "Theaterwissenschaft",
  "Theologie mit Schwerpunkt altkatholische Theologie",
  "Theologie mit Schwerpunkt evangelische Theologie",
  "Theologie",
  "Veterinärmedizin",
  "Volkswirtschaftslehre",
  "Wirtschaftsinformatik",
  "Wirtschaftsrecht",
  "Wissenschaftsphilosophie",
  "Zahnmedizin"
];
